name: LightPlatform Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  light-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run LightPlatform tests with coverage gating
        run: ./gradlew -p intellij-latex-plugin test lightTest jacocoTestReport jacocoTestCoverageVerification --no-daemon --stacktrace -DenableLightTests=true
        env:
          CI: true
